drop_cols = c(#columns with high percent of invalid observations and low gain
              'RATE_INTEREST_PRIMARY_mean',
              'RATE_INTEREST_PRIMARY_sum',
              'RATE_INTEREST_PRIVILEGED_mean',
              'RATE_INTEREST_PRIMARY_min',
              'RATE_INTEREST_PRIVILEGED_min',
              'RATE_INTEREST_PRIMARY_max',
              'RATE_INTEREST_PRIVILEGED_max',
              'RATE_INTEREST_PRIVILEGED_sum',
              # columns absent in the model for 5 iterations
              'FLAG_MOBIL',
              'FLAG_CONT_MOBILE',
              'FLAG_DOCUMENT_2',
              'FLAG_DOCUMENT_4',
              'FLAG_DOCUMENT_7',
              'FLAG_DOCUMENT_10',
              'FLAG_DOCUMENT_12',
              'FLAG_DOCUMENT_17',
              'FLAG_DOCUMENT_19',
              'FLAG_DOCUMENT_20',
              'FLAG_DOCUMENT_21',
              'CREDIT_CURRENCY_min',
              'CREDIT_DAY_OVERDUE_min',
              'CREDIT_CURRENCY_max',
              'CREDIT_CURRENCY_n_distinct',
              'AMT_CREDIT_SUM_OVERDUE_n_distinct',
              'AMT_DRAWINGS_OTHER_CURRENT_min',
              'CNT_DRAWINGS_OTHER_CURRENT_min',
              'NAME_CONTRACT_STATUS_min.x',
              'SK_DPD_min.x',
              'SK_DPD_DEF_min.x',
              'CNT_DRAWINGS_OTHER_CURRENT_n_distinct',
              'SK_DPD_DEF_n_distinct.x',
              'NUM_INSTALMENT_VERSION_min',
              'DPD_min',
              'NAME_CONTRACT_STATUS_min.y',
              'SK_DPD_min.y',
              'SK_DPD_DEF_min.y',
              'RATE_INTEREST_PRIMARY_sd',
              'RATE_INTEREST_PRIVILEGED_sd',
              'NAME_CONTRACT_STATUS_min',
              'FLAG_LAST_APPL_PER_CONTRACT_max',
              'NFLAG_LAST_APPL_IN_DAY_max',
              'FLAG_LAST_APPL_PER_CONTRACT_n_distinct',
              'RATE_INTEREST_PRIVILEGED_n_distinct',
              #columns with low importance < 1E-04
              'AMT_TOTAL_RECEIVABLE_sum',
              'NAME_CLIENT_TYPE_n_distinct',
              'AMT_DRAWINGS_OTHER_CURRENT_max',
              'REG_CITY_NOT_WORK_CITY',
              'LIVE_CITY_NOT_WORK_CITY',
              'CNT_DRAWINGS_CURRENT_n_distinct',
              'NAME_CASH_LOAN_PURPOSE_n_distinct',
              'NAME_PORTFOLIO_n_distinct',
              'CNT_DRAWINGS_ATM_CURRENT_n_distinct',
              'MONTHS_BALANCE_min_n_distinct',
              'AMT_CREDIT_n_distinct',
              'AMT_REQ_CREDIT_BUREAU_WEEK',
              'SK_DPD_sum.x',
              'STATUS_n_distinct_min',
              'AMT_PAYMENT_TOTAL_CURRENT_min',
              'CNT_DRAWINGS_POS_CURRENT_n_distinct',
              'STATUS_sum_n_distinct',
              'MONTHS_BALANCE_mean_n_distinct',
              'MONTHS_BALANCE_max_max',
              'AMT_DRAWINGS_OTHER_CURRENT_mean',
              'NAME_PRODUCT_TYPE_n_distinct',
              'AMT_ANNUITY_n_distinct.x',
              'AMT_INST_MIN_REGULARITY_min',
              'CREDIT_DAY_OVERDUE_max',
              'FLAG_LAST_APPL_PER_CONTRACT_sum',
              'MONTHS_BALANCE_sum_n_distinct',
              'RATE_INTEREST_PRIMARY_min',
              'FLAG_DOCUMENT_6',
              'CNT_INSTALMENT_MATURE_CUM_min',
              'REG_REGION_NOT_WORK_REGION',
              'FLAG_EMAIL',
              'STATUS_max_max',
              'NAME_PORTFOLIO_max',
              'AMT_DRAWINGS_OTHER_CURRENT_sum',
              'RATE_INTEREST_PRIMARY_max',
              'AMT_CREDIT_LIMIT_ACTUAL_n_distinct',
              'FLAG_DOCUMENT_11',
              'CREDIT_ACTIVE_n_distinct',
              'RATE_INTEREST_PRIVILEGED_mean',
              'CREDIT_ACTIVE_max',
              'AMT_DRAWINGS_OTHER_CURRENT_sd',
              'HOUSETYPE_MODE',
              'FLAG_DOCUMENT_16',
              'SK_DPD_max.x',
              'STATUS_n_distinct_n_distinct',
              'AMT_DRAWINGS_POS_CURRENT_min',
              'NFLAG_LAST_APPL_IN_DAY_sd',
              'NAME_CONTRACT_TYPE_max',
              'AMT_DRAWINGS_CURRENT_min',
              'CNT_DRAWINGS_POS_CURRENT_min',
              'CNT_DRAWINGS_OTHER_CURRENT_mean',
              'LIVE_REGION_NOT_WORK_REGION',
              'STATUS_max_n_distinct',
              'NAME_PAYMENT_TYPE_n_distinct',
              'CNT_CREDIT_PROLONG_max',
              'NAME_CONTRACT_TYPE_n_distinct',
              'CNT_DRAWINGS_OTHER_CURRENT_sd',
              'SK_DPD_DEF_sum.x',
              'NAME_PAYMENT_TYPE_min',
              'STATUS_max_min',
              'NAME_PAYMENT_TYPE_max',
              'CREDIT_DAY_OVERDUE_mean',
              'NAME_CLIENT_TYPE_max',
              'FLAG_LAST_APPL_PER_CONTRACT_mean',
              'CREDIT_DAY_OVERDUE_sum',
              'AMT_REQ_CREDIT_BUREAU_DAY',
              'NAME_CONTRACT_STATUS_max.x',
              'NFLAG_LAST_APPL_IN_DAY_sum',
              'EMERGENCYSTATE_MODE',
              'REG_REGION_NOT_LIVE_REGION',
              'FLAG_LAST_APPL_PER_CONTRACT_sd',
              'NFLAG_INSURED_ON_APPROVAL_n_distinct',
              'NAME_CASH_LOAN_PURPOSE_max',
              'NFLAG_INSURED_ON_APPROVAL_max',
              'NFLAG_LAST_APPL_IN_DAY_mean',
              'CREDIT_ACTIVE_min',
              'RATE_INTEREST_PRIVILEGED_sum',
              'STATUS_min_max',
              'CNT_CREDIT_PROLONG_sum',
              'NAME_CONTRACT_STATUS_n_distinct.x',
              'RATE_INTEREST_PRIMARY_sum',
              'STATUS_min_n_distinct',
              'NAME_CONTRACT_TYPE_min',
              'FLAG_DOCUMENT_5',
              'SK_DPD_DEF_max.x',
              'NFLAG_INSURED_ON_APPROVAL_min',
              'NAME_PORTFOLIO_min',
              'RATE_INTEREST_PRIVILEGED_min',
              'RATE_INTEREST_PRIVILEGED_max',
              'CNT_DRAWINGS_ATM_CURRENT_min',
              'FLAG_DOCUMENT_14',
              'SK_DPD_n_distinct.x',
              'NAME_PRODUCT_TYPE_max',
              'NFLAG_LAST_APPL_IN_DAY_n_distinct',
              'DAYS_FIRST_DRAWING_n_distinct',
              'FLAG_EMP_PHONE',
              'AMT_DRAWINGS_OTHER_CURRENT_n_distinct',
              'STATUS_min_min',
              'CODE_REJECT_REASON_max',
              'CNT_DRAWINGS_OTHER_CURRENT_sum',
              'FLAG_DOCUMENT_15',
              'CNT_CREDIT_PROLONG_n_distinct',
              'CNT_DRAWINGS_CURRENT_min',
              'FLAG_LAST_APPL_PER_CONTRACT_min',
              'AMT_REQ_CREDIT_BUREAU_HOUR',
              'CREDIT_CURRENCY_mean',
              'FLAG_DOCUMENT_13',
              'NUM_INSTALMENT_NUMBER_min',
              'FLAG_DOCUMENT_9',
              'CREDIT_CURRENCY_sd',
              'AMT_CREDIT_SUM_OVERDUE_min',
              'CNT_DRAWINGS_OTHER_CURRENT_max',
              'DAYS_FIRST_DRAWING_sd',
              'NFLAG_LAST_APPL_IN_DAY_min',
              'RATE_INTEREST_PRIMARY_n_distinct',
              'CNT_CREDIT_PROLONG_min',
              'CREDIT_DAY_OVERDUE_n_distinct',
              'AMT_DRAWINGS_ATM_CURRENT_min',
              #columns droped after the latest iterations
              'MONTHS_BALANCE_n_distinct_n_distinct',
              'MONTHS_BALANCE_sd_n_distinct',
              'AMT_TOTAL_RECEIVABLE_n_distinct',
              'CREDIT_ACTIVE_BOOL_n_distinct',
              'CREDIT_CLOSED_BOOL_min',
              'CREDIT_CLOSED_BOOL_n_distinct',
              'CREDIT_ACTIVE_BOOL_max',
              'CREDIT_CLOSED_BOOL_max',
              'CREDIT_SOLD_BOOL_max',
              'CREDIT_SOLD_BOOL_n_distinct',
              'CREDIT_SOLD_BOOL_sum',
              'CREDIT_ACTIVE_BOOL_min',
              'CREDIT_SOLD_BOOL_min'
            )

drop_cols_bureau = c(#columns with high percent of invalid observations and low gain
  'RATE_INTEREST_PRIMARY_mean',
  'RATE_INTEREST_PRIMARY_sum',
  'RATE_INTEREST_PRIVILEGED_mean',
  'RATE_INTEREST_PRIMARY_min',
  'RATE_INTEREST_PRIVILEGED_min',
  'RATE_INTEREST_PRIMARY_max',
  'RATE_INTEREST_PRIVILEGED_max',
  'RATE_INTEREST_PRIVILEGED_sum'
  # columns with low gain < 1E-04
  # 'AMT_CREDIT_n_distinct',
  # 'CNT_DRAWINGS_POS_CURRENT_n_distinct',
  # 'CNT_INSTALMENT_MATURE_CUM_min',
  # 'AMT_PAYMENT_TOTAL_CURRENT_min',
  # 'MONTHS_BALANCE_mean_n_distinct',
  # 'START_STATUS_sum_min',
  # 'AMT_REQ_CREDIT_BUREAU_WEEK',
  # 'NAME_CONTRACT_STATUS_n_distinct',
  # 'CREDIT_TYPE_min',
  # 'FLAG_DOCUMENT_6',
  # 'STATUS_sd_n_distinct',
  # 'DAYS_FIRST_DRAWING_max',
  # 'FLAG_DOCUMENT_8',
  # 'STATUS_WEIGHTED_sd_n_distinct',
  # 'NAME_PORTFOLIO_n_distinct',
  # 'START_STATUS_n_distinct_sum',
  # 'AMT_DRAWINGS_OTHER_CURRENT_max',
  # 'AMT_INST_MIN_REGULARITY_min',
  # 'MONTHS_BALANCE_sum_n_distinct',
  # 'AMT_TOTAL_RECEIVABLE_min',
  # 'DAYS_FIRST_DRAWING_sum',
  # 'NAME_CONTRACT_STATUS_max.x',
  # 'STATUS_n_distinct_n_distinct',
  # 'FLAG_EMAIL',
  # 'AMT_DRAWINGS_POS_CURRENT_min',
  # 'MONTHS_BALANCE_sd_n_distinct',
  # 'AMT_DRAWINGS_OTHER_CURRENT_sd',
  # 'STATUS_max_sum',
  # 'STATUS_min_mean',
  # 'CREDIT_TYPE_n_distinct',
  # 'MONTHS_BALANCE_n_distinct.x',
  # 'CREDIT_DAY_OVERDUE_sd',
  # 'NAME_CASH_LOAN_PURPOSE_n_distinct',
  # 'END_STATUS_min_sd',
  # 'AMT_DRAWINGS_OTHER_CURRENT_sum',
  # 'CREDIT_SOLD_BOOL_sd',
  # 'STATUS_WEIGHTED_mean_n_distinct',
  # 'END_STATUS_n_distinct_sum',
  # 'AMT_TOTAL_RECEIVABLE_sd',
  # 'AMT_TOTAL_RECEIVABLE_max',
  # 'AMT_BALANCE_n_distinct',
  # 'STATUS_n_distinct_max',
  # 'FLAG_LAST_APPL_PER_CONTRACT_mean',
  # 'END_STATUS_sum_n_distinct',
  # 'CNT_DRAWINGS_OTHER_CURRENT_mean',
  # 'SK_DPD_DEF_sum.x',
  # 'STATUS_WEIGHTED_max_n_distinct',
  # 'SK_DPD_DEF_sd.x',
  # 'MONTHS_BALANCE_min.x',
  # 'NAME_PAYMENT_TYPE_min',
  # 'CNT_DRAWINGS_ATM_CURRENT_n_distinct',
  # 'AMT_RECIVABLE_n_distinct',
  # 'STATUS_max_n_distinct',
  # 'AMT_DRAWINGS_CURRENT_min',
  # 'DAYS_FIRST_DUE_n_distinct',
  # 'AMT_DRAWINGS_OTHER_CURRENT_mean',
  # 'CNT_CREDIT_PROLONG_max',
  # 'NAME_CONTRACT_STATUS_n_distinct.y',
  # 'SK_DPD_DEF_n_distinct.y',
  # 'CREDIT_DAY_OVERDUE_max',
  # 'FLAG_DOCUMENT_13',
  # 'STATUS_WEIGHTED_n_distinct_n_distinct',
  # 'NFLAG_INSURED_ON_APPROVAL_max',
  # 'NAME_CLIENT_TYPE_max',
  # 'RATE_INTEREST_PRIMARY_n_distinct',
  # 'NAME_PORTFOLIO_max',
  # 'SK_DPD_max.x',
  # 'STATUS_WEIGHTED_sum_n_distinct',
  # 'STATUS_min_sum',
  # 'HOUSETYPE_MODE',
  # 'STATUS_n_distinct_min',
  # 'NAME_CASH_LOAN_PURPOSE_max',
  # 'CREDIT_DAY_OVERDUE_mean',
  # 'FLAG_LAST_APPL_PER_CONTRACT_sd',
  # 'NAME_PRODUCT_TYPE_n_distinct',
  # 'NUM_INSTALMENT_NUMBER_min',
  # 'NFLAG_LAST_APPL_IN_DAY_sd',
  # 'AMT_REQ_CREDIT_BUREAU_DAY',
  # 'CNT_DRAWINGS_OTHER_CURRENT_sd',
  # 'CNT_CREDIT_PROLONG_sum',
  # 'CREDIT_DAY_OVERDUE_sum',
  # 'START_STATUS_mean_sum',
  # 'END_STATUS_mean_sum',
  # 'AMT_TOTAL_RECEIVABLE_n_distinct',
  # 'REG_REGION_NOT_LIVE_REGION',
  # 'FLAG_DOCUMENT_11',
  # 'STATUS_mean_n_distinct',
  # 'START_STATUS_sum_max',
  # 'END_STATUS_min_sum',
  # 'START_STATUS_sum_n_distinct',
  # 'FLAG_EMP_PHONE',
  # 'NAME_PRODUCT_TYPE_max',
  # 'FLAG_LAST_APPL_PER_CONTRACT_sum',
  # 'STATUS_sum_n_distinct',
  # 'STATUS_WEIGHTED_min_min',
  # 'NAME_CONTRACT_TYPE_n_distinct',
  # 'NFLAG_LAST_APPL_IN_DAY_sum',
  # 'SK_DPD_n_distinct.x',
  # 'AMT_ANNUITY_n_distinct.x',
  # 'AMT_CREDIT_LIMIT_ACTUAL_n_distinct',
  # 'NAME_TYPE_SUITE_n_distinct',
  # 'CNT_DRAWINGS_POS_CURRENT_min',
  # 'FLAG_DOCUMENT_5',
  # 'NAME_PAYMENT_TYPE_n_distinct',
  # 'NFLAG_LAST_APPL_IN_DAY_mean',
  # 'NAME_PAYMENT_TYPE_max',
  # 'START_STATUS_min_sd',
  # 'CREDIT_CLOSED_BOOL_min',
  # 'START_STATUS_min_max',
  # 'CNT_DRAWINGS_OTHER_CURRENT_sum',
  # 'FLAG_DOCUMENT_14',
  # 'END_STATUS_min_mean',
  # 'RATE_INTEREST_PRIVILEGED_n_distinct',
  # 'NAME_CONTRACT_STATUS_min',
  # 'AMT_CREDIT_SUM_max_+_RATE_INTEREST_PRIMARY_sd',
  # 'NAME_CONTRACT_TYPE_max',
  # 'END_STATUS_mean_min',
  # 'CREDIT_UNTYPICAL_CURRENCY_sd',
  # 'START_STATUS_max_sd',
  # 'NAME_PORTFOLIO_min',
  # 'FLAG_CONT_MOBILE',
  # 'CNT_CREDIT_PROLONG_n_distinct',
  # 'START_STATUS_max_mean',
  # 'CREDIT_ACTIVE_BOOL_max',
  # 'CREDIT_UNTYPICAL_CURRENCY_mean',
  # 'AMT_DRAWINGS_ATM_CURRENT_min',
  # 'FLAG_DOCUMENT_9',
  # 'START_STATUS_min_mean',
  # 'NUM_INSTALMENT_VERSION_min',
  # 'STATUS_max_max',
  # 'SK_DPD_DEF_n_distinct.x',
  # 'SK_DPD_DEF_max.x',
  # 'AMT_DRAWINGS_OTHER_CURRENT_n_distinct',
  # 'END_STATUS_mean_max',
  # 'CNT_DRAWINGS_CURRENT_min',
  # 'CODE_REJECT_REASON_max'
)
